### ISSUE TITLE
error when i attack a webiste

### ISSUE THREAD

**Issue by emanueleriboldi** [cyborg24/wpbrute#1]
here is the error:

Traceback (most recent call last):
  File "C:\Users\  \Desktop\test_2\wpbrute\wpbrute.py", line 54, in <module>
    conn.request('POST',  '/xmlrpc.php', data)
  File "C:\Python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Python38\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Python38\lib\http\client.py", line 1402, in connect
    super().connect()
  File "C:\Python38\lib\http\client.py", line 917, in connect
    self.sock = self._create_connection(
  File "C:\Python38\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by cyborg24** [comment]
Make sure you have a network connection and the url to attack is correct.
